\set ON_ERROR_STOP on

DROP SCHEMA IF EXISTS prodavnica CASCADE;
CREATE SCHEMA prodavnica;

CREATE TABLE prodavnica.kategorije (
    kategorija_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv         text NOT NULL UNIQUE,
    opis          text
);

CREATE TABLE prodavnica.dobavljaci (
    dobavljac_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv        text NOT NULL,
    grad         text NOT NULL,
    drzava       text NOT NULL,
    email        text NOT NULL UNIQUE,
    telefon      text,
    ocena        numeric(3,2) CHECK (ocena BETWEEN 1 AND 5)
);

CREATE TABLE prodavnica.zaposleni (
    zaposleni_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ime              text NOT NULL,
    prezime          text NOT NULL,
    email            text NOT NULL UNIQUE,
    radno_mesto      text NOT NULL,
    sektor           text NOT NULL,
    menadzer_id      integer REFERENCES prodavnica.zaposleni(zaposleni_id),
    datum_zaposlenja date NOT NULL,
    plata            numeric(10,2) NOT NULL CHECK (plata > 0)
);

CREATE TABLE prodavnica.proizvodi (
    proizvod_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv              text NOT NULL,
    kategorija_id      integer NOT NULL REFERENCES prodavnica.kategorije(kategorija_id),
    dobavljac_id       integer NOT NULL REFERENCES prodavnica.dobavljaci(dobavljac_id),
    cena               numeric(10,2) NOT NULL CHECK (cena > 0),
    kolicina_na_stanju integer NOT NULL DEFAULT 0 CHECK (kolicina_na_stanju >= 0),
    tezina_kg          numeric(7,3),
    aktivan            boolean NOT NULL DEFAULT true,
    datum_povlacenja   date,
    datum_kreiranja    date NOT NULL
);

CREATE TABLE prodavnica.kupci (
    kupac_id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ime                text NOT NULL,
    prezime            text NOT NULL,
    email              text NOT NULL UNIQUE,
    grad               text NOT NULL,
    drzava             text NOT NULL,
    segment            text NOT NULL CHECK (segment IN ('maloprodaja','pravno lice','vip')),
    datum_registracije date NOT NULL,
    aktivan            boolean NOT NULL DEFAULT true
);

CREATE TABLE prodavnica.porudzbine (
    porudzbina_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kupac_id         integer NOT NULL REFERENCES prodavnica.kupci(kupac_id),
    zaposleni_id     integer REFERENCES prodavnica.zaposleni(zaposleni_id),
    datum_porudzbine date NOT NULL,
    status           text NOT NULL CHECK (status IN ('nova','plaćena','poslata','isporučena','otkazana','vraćena')),
    nacin_placanja   text NOT NULL CHECK (nacin_placanja IN ('kartica','pouzećem','prenos','paypal')),
    popust_procenat  numeric(5,2) NOT NULL DEFAULT 0 CHECK (popust_procenat BETWEEN 0 AND 100)
);

CREATE TABLE prodavnica.stavke_porudzbine (
    stavka_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    porudzbina_id   integer NOT NULL REFERENCES prodavnica.porudzbine(porudzbina_id) ON DELETE CASCADE,
    proizvod_id     integer NOT NULL REFERENCES prodavnica.proizvodi(proizvod_id),
    kolicina        integer NOT NULL CHECK (kolicina > 0),
    cena            numeric(10,2) NOT NULL CHECK (cena > 0),
    popust_procenat numeric(5,2) NOT NULL DEFAULT 0,
    UNIQUE (porudzbina_id, proizvod_id)
);

CREATE TABLE prodavnica.isporuke (
    isporuka_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    porudzbina_id   integer NOT NULL UNIQUE REFERENCES prodavnica.porudzbine(porudzbina_id) ON DELETE CASCADE,
    kurirska_sluzba text NOT NULL,
    datum_slanja    date NOT NULL,
    datum_isporuke  date,
    trosak_dostave  numeric(8,2) NOT NULL CHECK (trosak_dostave >= 0),
    broj_posiljke   text NOT NULL UNIQUE
);

CREATE TABLE prodavnica.recenzije (
    recenzija_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proizvod_id  integer NOT NULL REFERENCES prodavnica.proizvodi(proizvod_id),
    kupac_id     integer NOT NULL REFERENCES prodavnica.kupci(kupac_id),
    ocena        integer NOT NULL CHECK (ocena BETWEEN 1 AND 5),
    komentar     text,
    datum        date NOT NULL
);

CREATE INDEX ix_proizvodi_kategorija ON prodavnica.proizvodi(kategorija_id);
CREATE INDEX ix_proizvodi_dobavljac  ON prodavnica.proizvodi(dobavljac_id);
CREATE INDEX ix_porudzbine_kupac     ON prodavnica.porudzbine(kupac_id);
CREATE INDEX ix_porudzbine_zaposleni ON prodavnica.porudzbine(zaposleni_id);
CREATE INDEX ix_porudzbine_datum     ON prodavnica.porudzbine(datum_porudzbine);
CREATE INDEX ix_stavke_porudzbina    ON prodavnica.stavke_porudzbine(porudzbina_id);
CREATE INDEX ix_stavke_proizvod      ON prodavnica.stavke_porudzbine(proizvod_id);
CREATE INDEX ix_recenzije_proizvod   ON prodavnica.recenzije(proizvod_id);
CREATE INDEX ix_recenzije_kupac      ON prodavnica.recenzije(kupac_id);
CREATE INDEX ix_zaposleni_menadzer   ON prodavnica.zaposleni(menadzer_id);

COMMENT ON SCHEMA prodavnica IS 'Online prodavnica — demo domen';

COMMENT ON TABLE prodavnica.kategorije        IS 'Kategorije proizvoda';
COMMENT ON TABLE prodavnica.dobavljaci        IS 'Dobavljači proizvoda';
COMMENT ON TABLE prodavnica.zaposleni         IS 'Zaposleni; menadzer_id pokazuje na nadređenog (self-join)';
COMMENT ON TABLE prodavnica.proizvodi         IS 'Proizvodi u prodaji';
COMMENT ON TABLE prodavnica.kupci             IS 'Kupci';
COMMENT ON TABLE prodavnica.porudzbine        IS 'Porudžbine kupaca';
COMMENT ON TABLE prodavnica.stavke_porudzbine IS 'Stavke porudžbine — koji proizvod i u kojoj količini';
COMMENT ON TABLE prodavnica.isporuke          IS 'Isporuke porudžbina';
COMMENT ON TABLE prodavnica.recenzije         IS 'Recenzije proizvoda od strane kupaca';

COMMENT ON COLUMN prodavnica.proizvodi.cena                IS 'Cena po komadu u dinarima';
COMMENT ON COLUMN prodavnica.proizvodi.kolicina_na_stanju  IS 'Trenutna količina na stanju';
COMMENT ON COLUMN prodavnica.proizvodi.datum_povlacenja    IS 'Datum povlačenja iz prodaje; NULL = još uvek u prodaji';
COMMENT ON COLUMN prodavnica.kupci.segment                 IS 'Segment kupca: maloprodaja, pravno lice ili vip';
COMMENT ON COLUMN prodavnica.kupci.datum_registracije      IS 'Datum registracije kupca';
COMMENT ON COLUMN prodavnica.zaposleni.menadzer_id         IS 'Nadređeni zaposleni; NULL za direktora';
COMMENT ON COLUMN prodavnica.zaposleni.plata               IS 'Mesečna plata u dinarima';
COMMENT ON COLUMN prodavnica.porudzbine.status             IS 'Status: nova, plaćena, poslata, isporučena, otkazana, vraćena';
COMMENT ON COLUMN prodavnica.porudzbine.nacin_placanja     IS 'Način plaćanja: kartica, pouzećem, prenos, paypal';
COMMENT ON COLUMN prodavnica.porudzbine.popust_procenat    IS 'Popust na celu porudžbinu u procentima';
COMMENT ON COLUMN prodavnica.stavke_porudzbine.cena        IS 'Cena po komadu u trenutku porudžbine';
COMMENT ON COLUMN prodavnica.stavke_porudzbine.kolicina    IS 'Naručena količina proizvoda';
COMMENT ON COLUMN prodavnica.isporuke.datum_isporuke       IS 'Datum isporuke; NULL = još nije isporučeno';
COMMENT ON COLUMN prodavnica.isporuke.broj_posiljke        IS 'Broj za praćenje pošiljke';
COMMENT ON COLUMN prodavnica.recenzije.ocena               IS 'Ocena proizvoda od 1 do 5';
