\set ON_ERROR_STOP on

DROP SCHEMA IF EXISTS fakultet CASCADE;
CREATE SCHEMA fakultet;

CREATE TABLE fakultet.katedre (
    katedra_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv            text NOT NULL UNIQUE,
    skraceni_naziv   text NOT NULL UNIQUE,
    godina_osnivanja integer NOT NULL
);

CREATE TABLE fakultet.smerovi (
    smer_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv           text NOT NULL UNIQUE,
    katedra_id      integer NOT NULL REFERENCES fakultet.katedre(katedra_id),
    nivo_studija    text NOT NULL CHECK (nivo_studija IN ('osnovne','master','doktorske')),
    trajanje_godina integer NOT NULL CHECK (trajanje_godina BETWEEN 1 AND 4),
    ukupno_espb     integer NOT NULL
);

CREATE TABLE fakultet.profesori (
    profesor_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ime          text NOT NULL,
    prezime      text NOT NULL,
    zvanje       text NOT NULL CHECK (zvanje IN ('asistent','docent','vanredni profesor','redovni profesor')),
    katedra_id   integer NOT NULL REFERENCES fakultet.katedre(katedra_id),
    email        text NOT NULL UNIQUE,
    datum_izbora date NOT NULL,
    kabinet      text
);

CREATE TABLE fakultet.predmeti (
    predmet_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sifra       text NOT NULL UNIQUE,
    naziv       text NOT NULL,
    espb        integer NOT NULL CHECK (espb BETWEEN 1 AND 15),
    semestar    integer NOT NULL CHECK (semestar BETWEEN 1 AND 8),
    smer_id     integer NOT NULL REFERENCES fakultet.smerovi(smer_id),
    profesor_id integer NOT NULL REFERENCES fakultet.profesori(profesor_id),
    obavezan    boolean NOT NULL DEFAULT true
);

CREATE TABLE fakultet.studenti (
    student_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ime            text NOT NULL,
    prezime        text NOT NULL,
    broj_indeksa   text NOT NULL UNIQUE,
    email          text NOT NULL UNIQUE,
    smer_id        integer NOT NULL REFERENCES fakultet.smerovi(smer_id),
    godina_upisa   integer NOT NULL,
    grad           text NOT NULL,
    status         text NOT NULL CHECK (status IN ('aktivan','apsolvent','diplomirao','mirovanje','ispisan')),
    datum_rodjenja date NOT NULL
);

CREATE TABLE fakultet.upisi_predmeta (
    upis_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id     integer NOT NULL REFERENCES fakultet.studenti(student_id) ON DELETE CASCADE,
    predmet_id     integer NOT NULL REFERENCES fakultet.predmeti(predmet_id),
    skolska_godina text NOT NULL,
    datum_upisa    date NOT NULL,
    UNIQUE (student_id, predmet_id, skolska_godina)
);

CREATE TABLE fakultet.ispitni_rokovi (
    rok_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv          text NOT NULL,
    skolska_godina text NOT NULL,
    datum_pocetka  date NOT NULL,
    datum_kraja    date NOT NULL,
    UNIQUE (naziv, skolska_godina),
    CHECK (datum_kraja >= datum_pocetka)
);

CREATE TABLE fakultet.prijave_ispita (
    prijava_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upis_id       integer NOT NULL REFERENCES fakultet.upisi_predmeta(upis_id) ON DELETE CASCADE,
    rok_id        integer NOT NULL REFERENCES fakultet.ispitni_rokovi(rok_id),
    datum_prijave date NOT NULL,
    bodovi        integer CHECK (bodovi BETWEEN 0 AND 100),
    ocena         integer CHECK (ocena BETWEEN 5 AND 10),
    polozen       boolean NOT NULL DEFAULT false,
    UNIQUE (upis_id, rok_id)
);

CREATE INDEX ix_smerovi_katedra    ON fakultet.smerovi(katedra_id);
CREATE INDEX ix_profesori_katedra  ON fakultet.profesori(katedra_id);
CREATE INDEX ix_predmeti_smer      ON fakultet.predmeti(smer_id);
CREATE INDEX ix_predmeti_profesor  ON fakultet.predmeti(profesor_id);
CREATE INDEX ix_studenti_smer      ON fakultet.studenti(smer_id);
CREATE INDEX ix_upisi_student      ON fakultet.upisi_predmeta(student_id);
CREATE INDEX ix_upisi_predmet      ON fakultet.upisi_predmeta(predmet_id);
CREATE INDEX ix_prijave_upis       ON fakultet.prijave_ispita(upis_id);
CREATE INDEX ix_prijave_rok        ON fakultet.prijave_ispita(rok_id);

COMMENT ON SCHEMA fakultet IS 'Fakultet — studenti, predmeti i ispiti';

COMMENT ON TABLE fakultet.katedre        IS 'Katedre na fakultetu';
COMMENT ON TABLE fakultet.smerovi        IS 'Studijski programi (smerovi)';
COMMENT ON TABLE fakultet.profesori      IS 'Nastavno osoblje';
COMMENT ON TABLE fakultet.predmeti       IS 'Predmeti; svaki pripada jednom smeru i jednom predmetnom nastavniku';
COMMENT ON TABLE fakultet.studenti       IS 'Studenti';
COMMENT ON TABLE fakultet.upisi_predmeta IS 'Koji student je koji predmet upisao u kojoj školskoj godini (veza M:N)';
COMMENT ON TABLE fakultet.ispitni_rokovi IS 'Ispitni rokovi po školskoj godini';
COMMENT ON TABLE fakultet.prijave_ispita IS 'Prijave ispita sa rezultatom; NULL ocena znači da student nije izašao na ispit';

COMMENT ON COLUMN fakultet.smerovi.nivo_studija         IS 'Nivo studija: osnovne, master ili doktorske';
COMMENT ON COLUMN fakultet.smerovi.ukupno_espb          IS 'Ukupan broj ESPB bodova potreban za završetak smera';
COMMENT ON COLUMN fakultet.profesori.zvanje             IS 'Zvanje: asistent, docent, vanredni profesor, redovni profesor';
COMMENT ON COLUMN fakultet.predmeti.sifra               IS 'Šifra predmeta, na primer RN-101';
COMMENT ON COLUMN fakultet.predmeti.espb                IS 'Broj ESPB bodova koje predmet nosi';
COMMENT ON COLUMN fakultet.predmeti.semestar            IS 'Semestar u kome se predmet sluša (1-8)';
COMMENT ON COLUMN fakultet.predmeti.obavezan            IS 'true = obavezan predmet, false = izborni';
COMMENT ON COLUMN fakultet.studenti.broj_indeksa        IS 'Broj indeksa u formatu godina/redni broj';
COMMENT ON COLUMN fakultet.studenti.status              IS 'Status: aktivan, apsolvent, diplomirao, mirovanje, ispisan';
COMMENT ON COLUMN fakultet.upisi_predmeta.skolska_godina IS 'Školska godina upisa predmeta, na primer 2024/2025';
COMMENT ON COLUMN fakultet.prijave_ispita.bodovi        IS 'Osvojeni bodovi 0-100; NULL ako student nije izašao na ispit';
COMMENT ON COLUMN fakultet.prijave_ispita.ocena         IS 'Ocena 5-10; NULL ako student nije izašao na ispit';
COMMENT ON COLUMN fakultet.prijave_ispita.polozen       IS 'true ako je ispit položen (ocena veća od 5)';
