-- =====================================================================
-- 05_aplikacija_meta.sql — šema "aplikacija" (radni podaci same aplikacije)
--
-- Ovo NISU demo podaci nad kojima se filtrira. Ovde aplikacija čuva:
--   - istoriju upita koje je korisnik postavio,
--   - rezultate testiranja modela (benchmark), iz kojih se crtaju grafikoni.
--
-- Read-only rola iz skripte 06 NEMA pristup ovoj šemi — SQL koji generiše
-- model ne sme ni da vidi ni da menja radne podatke aplikacije.
--
-- Pokretanje: psql -U postgres -d sqleval -f Baza/05_aplikacija_meta.sql
-- =====================================================================
\set ON_ERROR_STOP on

DROP SCHEMA IF EXISTS aplikacija CASCADE;
CREATE SCHEMA aplikacija;

-- Istorija upita iz aplikacije (tab "Istorija").
CREATE TABLE aplikacija.istorija_upita (
    upit_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pitanje          text NOT NULL,
    jezik            text NOT NULL CHECK (jezik IN ('sr','en')),
    baza             text NOT NULL,
    izabrane_tabele  text[],
    model_id         text NOT NULL,
    generisani_sql   text,
    ocena_sudije     integer CHECK (ocena_sudije BETWEEN 1 AND 5),
    obrazlozenje     text,
    izvrsen          boolean NOT NULL DEFAULT false,
    broj_redova      integer,
    trajanje_ms      integer,
    greska           text,
    kreirano         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_istorija_kreirano ON aplikacija.istorija_upita(kreirano DESC);

-- Jedno pokretanje benchmarka nad celim test setom.
CREATE TABLE aplikacija.benchmark_pokretanje (
    pokretanje_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pocetak         timestamptz NOT NULL DEFAULT now(),
    kraj            timestamptz,
    model_sudije    text NOT NULL,
    broj_zadataka   integer,
    napomena        text
);

-- Rezultat za jedan par (zadatak, model, jezik) unutar jednog pokretanja.
-- UNIQUE ograničenje omogućava nastavak prekinutog pokretanja (--resume):
-- već upisani parovi se preskaču i kvota besplatnog API tiera se ne troši ponovo.
CREATE TABLE aplikacija.benchmark_rezultat (
    rezultat_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokretanje_id     integer NOT NULL REFERENCES aplikacija.benchmark_pokretanje(pokretanje_id) ON DELETE CASCADE,
    zadatak_id        text NOT NULL,
    tezina            text NOT NULL CHECK (tezina IN ('lak','srednji','tezak')),
    model_id          text NOT NULL,
    jezik             text NOT NULL CHECK (jezik IN ('sr','en')),
    generisani_sql    text,
    sql_ispravan      boolean NOT NULL DEFAULT false,
    greska_izvrsavanja text,
    rezultat_isti     boolean NOT NULL DEFAULT false,
    ocena_sudije      integer CHECK (ocena_sudije BETWEEN 1 AND 5),
    sudija_tacan      boolean,
    obrazlozenje      text,
    trajanje_ms       integer,
    ulazni_tokeni     integer,
    izlazni_tokeni    integer,
    kreirano          timestamptz NOT NULL DEFAULT now(),
    UNIQUE (pokretanje_id, zadatak_id, model_id, jezik)
);

CREATE INDEX ix_rezultat_model  ON aplikacija.benchmark_rezultat(model_id);
CREATE INDEX ix_rezultat_tezina ON aplikacija.benchmark_rezultat(tezina);

COMMENT ON SCHEMA aplikacija IS 'Radni podaci aplikacije — istorija upita i rezultati benchmarka';

COMMENT ON TABLE  aplikacija.istorija_upita        IS 'Istorija pitanja postavljenih u aplikaciji';
COMMENT ON TABLE  aplikacija.benchmark_pokretanje  IS 'Jedno pokretanje testa nad celim test setom';
COMMENT ON TABLE  aplikacija.benchmark_rezultat    IS 'Rezultat za jedan par zadatak-model-jezik';

COMMENT ON COLUMN aplikacija.istorija_upita.baza            IS 'Nad kojom šemom je upit postavljen: prodavnica ili fakultet';
COMMENT ON COLUMN aplikacija.benchmark_rezultat.sql_ispravan  IS 'Generisani SQL se izvršio bez greške';
COMMENT ON COLUMN aplikacija.benchmark_rezultat.rezultat_isti IS 'Execution accuracy — rezultat je identičan rezultatu gold SQL-a';
COMMENT ON COLUMN aplikacija.benchmark_rezultat.sudija_tacan  IS 'Da li se ocena sudije poklopila sa execution accuracy';
