<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SqlQueryEvaluator.Core\SqlQueryEvaluator.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5f31053c-de05-415a-b665-944b217e91fd</UserSecretsId>
  </PropertyGroup>

</Project>
